name: Python Master Workflow
on:
  push:
    branches:
      - 'master'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          flags: unittests
